services:
  nextjs-app:
    image: ghcr.io/alihanii/abra-front:latest
    container_name: nextjs_container
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: always
